### ISSUE TITLE
Cant login to eve

### ISSUE THREAD

**Issue by Genosse-X** [EVEIPH/EVE-IPH#105]
i have setted up the registration and then tried to login here
https://i.gyazo.com/1cf89916c1913a6560240fc20b0ce767.png

the i get this error:
https://i.gyazo.com/0dc514c2f8b833dfb293e60a803595fc.png

here should be all fine:
https://i.gyazo.com/a94555608a1e030f8395f9901a851110.png

**Comment by Zifrian** [comment]
Are you using chrome as your default browser by chance? Users are having issues with it as it won't call back to local host. See if you get the same error with another browser set to default.

**Comment by Genosse-X** [comment]
Hi, i use Firefox, tried it now with IE, but there i get Badrequest 400

**Comment by Genosse-X** [comment]
when i authorzi with evernus, it works all fine.

**Comment by Zifrian** [comment]
Applied Ben's fix in Build 4.0.6758.39841. Let me know if it's still an issue.
