### ISSUE TITLE
ME/TE/Cost bonus don't apply to tab that is not selected by default

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#106]
E.g. If you select a Hel blueprint, setting the structures for manufacturing affects the ME/TE bonuses shown.

However, going to cap manufacturing tab and selecting a new structure and adding the rigs does not update the ME/TE bonuses shown and listed quantities of minerals does not update.

Version 19468

**Comment by Zifrian** [comment]
This should be fixed with Build 4.0.6825.38684.

**Comment by zductiv** [comment]
I'm not seeing any changes to this behaviour on 4.0.6828.39286

**Comment by Zifrian** [comment]
OK I see it now. I'll take a look. Thanks

**Comment by zductiv** [comment]
Now does work, however, the first time putting in your rigs, the values don't updated on the window. You have to change tabs and come back before it will show the updated ME / TE values. Also, once you've done that and the screen is now showing the correct ME/TE values, you then have to hit the refresh button to get the updated values.

**Comment by Zifrian** [comment]
OK thanks. I made a few more changes. See how that works out.
