### ISSUE TITLE
Update: ESI_CORPORATION_DATA has 19 columns but 20 values were supplied

### ISSUE THREAD

**Issue by radub7** [EVEIPH/EVE-IPH#108]
I have a problem updating version 4.0.6746.19468. The updater throws a message (screenshots attached) that says "Table ESI_CORPORATION_DATA has 19 columns but 20 values were supplied."
This happens when I start EVE IPH, or when I try to update from within the app, About -> Check for updates.
![eveiph updater_2018-06-27_20-02-10](https://user-images.githubusercontent.com/28403211/41988842-07a09464-7a46-11e8-98ae-03fb66ec775b.png)
![eveiph updater_2018-06-27_20-02-20](https://user-images.githubusercontent.com/28403211/41988843-0a9cbe0e-7a46-11e8-91ed-9b2b4e9f0346.png)

**Comment by radub7** [comment]
As of June 30, 2018 10:30 UTC the problem appears to be solved - the update ran without issues.
I'm closing this ticket - thanks !

**Comment by radub7** [comment]
It still doesn't works - same issue as above. It _seemed_ to work once, but I closed the app and re-opened it, it asked again to update, and same issue as above ...

**Comment by Zifrian** [comment]
Can you contact me in game? Not sure why this is happening but I think it's unique to your character maybe.

**Comment by radub7** [comment]
I've solved the problem by uninstalling the program, then searching and deleting manually every IPH file in the user profile, then reinstalling. The problem does not appears anymore. I'm closing this ticket for good - it was my fault !
