### ISSUE TITLE
Partially working “Add items to the shopping list by right clicking the item and selecting add to shopping list"

### ISSUE THREAD

**Issue by Crystal4276** [EVEIPH/EVE-IPH#114]
“Add items to the shopping list by right clicking the item and selecting add to shopping list again.”

If done on T2 items with a calculation on raw materials, the components are not shown in the shopping list.

Tested on blueprint tab without issue, only manufacturing tab is problematic

**Comment by Zifrian** [comment]
This is fixed in Build 4.0.6825.38684. Let me know if you have any issues.
