### ISSUE TITLE
no such table: ESI_CHARACTER_DATA

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-IPH#116]
Hi

With a clean start (so no DB) i get a 

> no such table: ESI_CHARACTER_DATA

 error at line 165 in LoadDefaultCharacter,

**Comment by wvdvegt** [comment]
Think i got it, you moved the database creation into a separate tool. Adding a message that the database is missing and the tools needs to be re-run would not harm user friendliness.

**Comment by Zifrian** [comment]
Are you talking about in debug mode or the actual application?
