### ISSUE TITLE
Updater downloading in C:\Program Files (x86)\EVE IPH\

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-IPH#117]
Hi

Just ran the EVEIPH Updater.exe and it still downloads where it should not do so (i.e. under program files). To be more precise it seems to make a subdirectory relative to it's startup directory (I unzipped all from the EVEIPH v4.0 Binaries under program files and ran the updater from there).

**Comment by wvdvegt** [comment]
After running the updater i seem to have two eveiph executables, one under program files where the msi installer put stuff and one from where the updater was run (i ran it also under %appdata%\eve iph).

**Comment by Zifrian** [comment]
The installer puts the files in the app data folder that change regularly. The EXE is in program files. 

When the updater runs, it should update both locations and cleanup any extra files. I haven't noticed an issue with this lately. Maybe double check and see if there is still an issue. Some screenshots would help as well.

Also, are you doing this in debug mode or is this stand alone?

**Comment by Zifrian** [comment]
After testing, I'm not seeing this issue. I've also updated to allow installations on other drives than the C drive. If you have this issue still, please update with more information and I'll re-open.
