### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Zumochi** [EVEIPH/EVE-IPH#12]
I guess it would be nice to have a readme in the root of the project linking to downloads, contact, credits and other pages (help etc.)

**Comment by Kev** [comment]
It'd be great if this could include a brief "Development: Getting Started" to cover fetching dependencies in an appropriate way, etc. (I had trouble with this, although I'm not really a .Net dev, so maybe it's all my inexperience).

**Comment by Pilchard123** [comment]
I can take this one on, if you like.

**Comment by Cwittofur** [comment]
This shouldn't be an issue once I get the dependencies properly checked in.

**Comment by Kev** [comment]
A comment about needing to import a DB from the release zip, or to generate one yourself from the other repo, might be useful (took me a while to realise that). I could easily make such a change to the README if you liked.

**Comment by Cwittofur** [comment]
Information regarding building is part of the read me on the repo stub
page.

**Comment by Pilchard123** [comment]
Is checking in all of the dependencies in necessarily the best course? Once it's set up, NuGet will re-download packages that it manages on build if they are missing. As far as I can see, all of the DLLs that are used are available there. There'd have to be a bit of work to move to NuGet, but it would mean that they were all stored in one place and came from one place.

**Comment by Zifrian** [comment]
Gesh, I decide to leave and people hop out of the woodwork to support. Do I smell? Either way, fantastic! Appreciate the collaboration!

On the dependencies, we had an issue pushing it out to the user through the update the other day and had to revert to what people had on their machines (ZipForge) and then Cwittofur will push the Ionic.dll out for a few months to ensure people can run it. NuGet is great, but I had to manually do the updating in VS Express. I agree that we should be able to get those libraries updated easily but I was really only thinking about the user. Copying a dll to the directory for me isn't a big deal, deploying a workable product is more of a pain to keep consistent.

**Comment by Pilchard123** [comment]
Personally, I avoided helping because I didn't want to make you feel you had to carry on support if you didn't want to. 

What version of VS are you using? If you're using an Express edition, have you looked at [Visual Studio Community](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx)? It's free for OS projects, among other things. I don't use it myself (I have 2015 Enterprise), but I'm pretty sure that's got NuGet included. You also get some pretty cool toys in the updated language spec

**Comment by Pilchard123** [comment]
It occurred to me that there's no explicit license attached to this. That, at least, should probably be added.

**Comment by Pilchard123** [comment]
It struck me that there is no explicit license on this. Should there be?

http://choosealicense.com/

**Comment by Cwittofur** [comment]
I would say the MIT license is probably the best, but Zifrian should decide
on this :)

**Comment by Kev** [comment]
You'll need agreement from any previous contributors to change (or set) a license. So to make things a little easier and save time - I'm happy with my recent (trivial) contribution being placed under MIT.
