### ISSUE TITLE
Manual changes to some prices and citadel stats does not stay saved

### ISSUE THREAD

**Issue by brinelan** [EVEIPH/EVE-IPH#121]
When I change the prices for compressed ore either in the material list section or in the using the menu in Edit > Prices > Item search tab the prices do not update.

Tax rates for citadels do not stay saved.  Also facilities keep reverting to their default values of Jita or Providence as well.

**Comment by Zifrian** [comment]
The compressed ores do save but for some reason the price doesn't change on the BP tab. I didn't write that code and I need to update it. So for now, it'll go on the to-do list.

On tax rates for citadels, I'm not seeing an issue. Can you send me more details? When do you see them not saved? 

On the facilities changing, when? On startup? When are they reverting? I need more details to debug. Thanks

**Comment by brinelan** [comment]
When I noticed the facilities reverting back to their defaults, I was changing between two characters since my scanned BPO collection's me/te values were only showing on the character that did the scan.  I stopped changing characters and now manually update the me values and the facilities have not reverted since.

**Comment by Zifrian** [comment]
OK, yeah the facilities are saved per character now. I'll try and add an option to turn that off as well as with BPs.

The compressed ore price changes will be fixed next patch.
