### ISSUE TITLE
Unable to set tax rate on structures

### ISSUE THREAD

**Issue by brinelan** [EVEIPH/EVE-IPH#124]
When setting the tax rate for a citadel on the Blueprints tab and the Manufacturing list tab, the tax rate message says it saves but the value reverts back to 0% tax during use pulling up different items.

**Comment by Zifrian** [comment]
Can you give an example? I'm not seeing this.

**Comment by brinelan** [comment]
I select the tax rate on the blueprints tab (Rorqual is selected).
Select an engineering complex that I have access to
Enter 8 for 8%
Hit tab
Hit Save
Change to another item and the tax rate is cleared.
Change back to the first item and the tax rate is back at 0

**Comment by Zifrian** [comment]
Still not seeing it. Working fine as far as I can tell. Can you send me a screenshot?

**Comment by Zifrian** [comment]
Will re-open if I get more information.
