### ISSUE TITLE
Building from raw / intermediate moon materials

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#125]
When you have settings set to build from raw or intermediate moon materials, and you add the raw materials or build/buy components the shopping list doesn't provide the qty of raw reactions/intermediate reactions to complete, or fuel blocks to build.

Not sure if that is the desired behaviour or not. I don't know about others but I'd like to be able to see all the reaction steps I need to do.

**Comment by Zifrian** [comment]
I made several fixes for reactions for raw and intermediate types while adding to shopping list in Build 4.0.7210.42162. Please check and resubmit bugs if needed.
