### ISSUE TITLE
Reaction jobs not showing in industry viewer

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#128]
Per title. Reaction jobs do not show up in the industry jobs viewer.

**Comment by Zifrian** [comment]
Damn, and I thought this was an easy fix! 

Thanks, I'll take a look.

**Comment by Zifrian** [comment]
Fixed in Build 4.0.6895.33941. Made some changes to the UI to give it a bit more room as well.

**Comment by zductiv** [comment]
I'm still finding this a little sticky in terms of sometimes it just seems to ignore characters that you have selected to retrieve their jobs but I can't find a way to try to reproduce it.

I had 2 chars selected and it refused to update for one of them, but when I selected another character that was not in the corp the character is in that had missing jobs, the update jobs then worked. Not sure if just coincidence or not though.

If I find a way to reproduce will let know.
