### ISSUE TITLE
Update Prices: Error on downloading prices

### ISSUE THREAD

**Issue by tash** [EVEIPH/EVE-IPH#131]
![grafik](https://user-images.githubusercontent.com/477569/48672010-a8ef1b00-eb30-11e8-8da0-acfd5fbf0a8a.png)

![grafik](https://user-images.githubusercontent.com/477569/48672003-8826c580-eb30-11e8-80d0-9f557aedb9c1.png)

After pressing [Download Prices] the process ends successfully with "Refreshing List". Unfortunately, this error dialog appears 14 times:

![grafik](https://user-images.githubusercontent.com/477569/48671998-734a3200-eb30-11e8-8732-c61cf5a56a60.png)

**Comment by Zifrian** [comment]
I can't reproduce this. What does the text on the bottom bar say when the error comes up? I think it might be a temporary ESI issue?

**Comment by tash** [comment]
The bottom bar remains as shown in the second screenshot.

**Comment by tash** [comment]
this is still reproducable for me, thus the likehood being an ESI issue is low.

**Comment by tash** [comment]
yes, this happens every time.
![grafik](https://user-images.githubusercontent.com/477569/48736171-d29c6500-ec4a-11e8-9718-81b70ea20184.png)

**Comment by Zifrian** [comment]
It doesn't look like you are using the profiles for anything. Can you try 'Single Select' and see if you get the same error?

**Comment by tash** [comment]
Same error.
If "Cancel Update" with either I get the same error as well. BUt this time a lot more dialogs than 14.

**Comment by Zifrian** [comment]
Yeah, I see the issue now. The error is coming back in german and I have it set to ignore that error in english since I can't get the error number for some reason. Let me figure out how to work around that.

**Comment by Zifrian** [comment]
OK put up a potential fix. See if that works now.

**Comment by tash** [comment]
Issues is resolved, thank you!
