### ISSUE TITLE
Support Corp Divisions in Asset viewer.

### ISSUE THREAD

**Issue by SylvainMT** [EVEIPH/EVE-IPH#132]
If possible please support corp divisions in the Asset explorer.  When you go to View > Assets you are given a screen of all the assets that were scanned by the application for the selected character. Under the heading "Corporate Assets" you have a selection of offices that are rented in NPC (and I assume Upwell Structures). Expanding that gives you the "Office" heading, and expanding that lists all the assets in all the corp divisions. For those like me that use a specific corp division for "Raw Materials," it would be advantages for the shopping list to use only the contents of that particular division and ignore the rest... Thanks

P.S. I realize that the interim fix would likely be the use of containers. which I'll be implementing soon.

**Comment by Zifrian** [comment]
This is fixed in Build 4.0.6963.23544.
