### ISSUE TITLE
Research chance not correctly calculated

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#134]
Invention chance in EVE IPH differs from that shown in-game.

Imported skills for the default character match.

Templar II for example with all invent skills at 3
![image](https://user-images.githubusercontent.com/8939440/49326670-c096bc80-f590-11e8-8e95-23c530f648ed.png)

Shows 46.8% in-game vs 43.35% in EVE IPH for no decryptor (invention time is also off, 21:40:30 in eve iph vs 21:30:06 in eve (no implant))

Decryptor | In-game | eve iph
Accel | 56.1 | 52.02
Attain | 84.2 | 78.03
Aug | 28.1 | 26.01
Opt Atta | 88.8 | 82.37
Opt Aug | 42.1 | 39.02
Parity | 70.1 | 65.03
Process | 51.4 | 47.69
Symm | 46.8 | 43.35

**Comment by zductiv** [comment]
Can't find a single reference to the formula being updated since phoebe. Is this an in-game display bug?

**Comment by Zifrian** [comment]
The formula is in the blueprints class under SetInventionChance. Figured it out though, the cap ships construction wasn't being considered in the total invention chance. I thought only science skills applied but apparently not. I'll push this fix next update.

The times might be a little off but in IPH, I multiply the times by the number of runs you will need to run. I'd have to know how you calculated the time above.

**Comment by Zifrian** [comment]
I've updated the formula in this patch 4.0.6963.23544 and it should affect your drone invention chance. Let me know if you still have an issue and I'll reopen.
