### ISSUE TITLE
ESI endpoint needs to be moved off of esi.tech.ccp.is to esi.evetech.net

### ISSUE THREAD

**Issue by ApatheticsAnonymous** [EVEIPH/EVE-IPH#136]
background:

> Earlier today, ESI had a few issues. As those issues were resolved, the redirect which had been in place for http://esi.tech.ccp.is to https://esi.evetech.net (the new address) was removed.
>
>CCP Bartender apparently showed up on the Tweetfleet Slack and posted this message:
>
>I'm working on getting a dev blog on the tech.ccp.is thing out, but I'm not allowed to press the buttons myself however, in the mean time, here's what's planned to be in the blog in case people need to tell other people:
>
>Greetings Developers! It's been a day of some disruption to ESI, for which Tech Co apologises. During the process of resolving today’s issues it was necessary to discard the DNS entries for esi.tech.ccp.is. As a result, ESI is now only available on https://esi.evetech.net/
>
>The esi.evetech.net URL has been the standard URL for ESI for approximately 6 months now, and the redirect from tech.ccp.is has been in place as a courtesy to allow developers some time for transition. It seems that Tech Co's communication on this matter has been below our desired standard and although most developers made the switch some time ago, not all developers were aware. For that too, we apologise.
>
>For reference, the matter has been discussed on the #esi tweetfleet slack and was alluded to in a dev blog ( https://developers.eveonline.com/blog/article/esi-march-news ) but was only explicitly stated in a tweet( https://twitter.com/TeamTechCo/status/992049219056812032 ), which we do not consider a core communication tool.
>
>Even so, we have considered the situation and have decided not to reinstate the redirect. Our reason for this decision is twofold: There has been a very reasonable amount of time to make this switch, and we do not wish to muddy the waters on this matter yet further.
>
>For the foreseeable future, ESI is now only on the URL https://esi.evetech.net/
>
>Carry on!
>
>Team Tech Co.

source: https://www.reddit.com/r/Eve/comments/a7sc0p/ccp_removes_redirect_from_old_httpsesitechccpis/

**Comment by Zifrian** [comment]
Thanks, was just able to get to this now. I've updated it in build 4.0.6927.39394. Should be good to go now.
