### ISSUE TITLE
Compression calculation

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#137]
The compressed ore calculations do not seem to have been updated to support the new refineries.

Perhaps when use compressed ore is checked, it could open up a drop down under activity for refinery, then allow you to select t1/t2 rigged athanor/tatara.

https://forums.eveonline.com/t/what-is-the-new-ore-refining-formula-for-athanor-and-tatara-citadels/38090/25?
updated formula

Drop downs to allow the use of null/low/high sec ores in the optimisation would be nice.

Adding an ore optimisation to the shopping list would be useful as well when you've added a whole bunch of minerals.

**Comment by Zifrian** [comment]
This isn't code I put in so I'll be replacing it at some point with something more functional. My original plan was to add a mining calc to the shopping list only. It's on the list.

**Comment by Zifrian** [comment]
I've removed this option for now. I'll try to add later.
