### ISSUE TITLE
SVR not being shown

### ISSUE THREAD

**Issue by Keridos** [EVEIPH/EVE-IPH#141]
v 4.0.6970.40574
SVR is not available for most items since a few days for me. Using The Forge and avg. of 30 days.

**Comment by Zifrian** [comment]
Try and reset the market history/orders from the Data menu/Reset Data first. I did make some changes to try and fix some long standing issues with loss of SVR data over time. Let me know how that goes and I'll keep an eye on it to see if I need to look at it again.

**Comment by Keridos** [comment]
This seems to have fixed it, maybe doing that automatically on that update would've been better :-)

**Comment by Zifrian** [comment]
I don't want to delete history data if I can help it. Plus updating it takes a bit of time if I were to refresh on upload.

Let me know if it pops up again. This is a long-standing issue I'm trying to fix.
