### ISSUE TITLE
Allow change of ME/TE for T2 BP

### ISSUE THREAD

**Issue by namachieli** [EVEIPH/EVE-IPH#142]
Currently with a T2 BP selected, ME and TE are greyed out and set to 2 and 4. Is it possible to allow this setting to be modified?

Thanks

**Comment by Zifrian** [comment]
Check 'Invention' under the Ignore in Calcs section and it will let you modify them. The only ME/TE values that can come up from invention are allowed when it's considering invention. If you turn this off, then it assumes you have a copy from a T2 BPO, legacy BPC, or a BPC from exploration (e.g. Rig BPCs), which aren't invented through normal processes.

**Comment by namachieli** [comment]
Excellent. thank you!
