### ISSUE TITLE
Seems wrong...

### ISSUE THREAD

**Issue by Queueyou** [EVEIPH/EVE-IPH#144]
With the newest version (updated it today) it seems that the 'sell excess' is a hugely awesome thing!  Makes calculating for single runs so much better.  But as an example, I attempted a Hulk...

1 run: https://i.gyazo.com/f8de9dd60a1b316de1e02552c66faf0f.png
10 runs: https://i.gyazo.com/1bd67b27da6b49aa89c50dd056bd8fd1.png

The 10 runs says it needs nearly 6bil in materials?  But the single run says it needs only 200mil.

Perhaps there is something I'm missing, but nothing changed between saying 1 run and 10 runs in my settings.

**Comment by Queueyou** [comment]
Maybe this will help too:
https://cdn.discordapp.com/attachments/471165319688224778/628033736553922570/unknown.png

**Comment by Zifrian** [comment]
I'll take a look but I noticed this happening and it looked ok in my tests, even if it looks crazy sometimes. Anyway, I'll double check. Thanks for the report.

**Comment by Queueyou** [comment]
Last update it was about a 1-2% profit when building 10 ships.  I changed nothing after updating.  I mean, maybe it is that crazy, but that's a HUGE difference.

Especially when a quick glance on fuzzworks just default/HS settings shows:
https://www.fuzzwork.co.uk/blueprint/?typeid=22544
Item Unit Price	238,999,997.91
Job Material Cost	3,302,307,910.16
Job Base Price	1,672,678,716.40
Install Price	215,608,286.54

**Comment by Zifrian** [comment]
This should be fixed now with Build 4.0.7217.24166
