### ISSUE TITLE
'Calculate Build/Buy' is not including the cost of constructable 'Buy' items or adding them to shopping lists

### ISSUE THREAD

**Issue by eve-n0rman** [EVEIPH/EVE-IPH#145]
With the most recent version (4.0.7217.24166) when you have 'Calculate Build/Buy' selected, 'Buy' items are not being considered in the costs or added to the shopping lists.  See screenshots, paying attention to the 'Buy' status of Nanoelectrical Microprocessor, and it's missing cost in the totals and not being added to the shopping list.  The buys for Morphite and Construction Blocks appear to be included in both the shopping list and costs, presumably because they're not something you can build.

![Nanoelectrical Microprocessor Buy costs](https://i.imgur.com/37hfqes.png)

![Missing Nanoelectrical Micropressor in shopping list](https://i.imgur.com/IUzoOij.png)

**Comment by Zifrian** [comment]
Fix up - Build 4.0.7217.40309

Sorry about that. Thanks for the bug report!
