### ISSUE TITLE
IPH crashes if the shopping list is sorted and you change the items

### ISSUE THREAD

**Issue by Regner** [EVEIPH/EVE-IPH#15]
Repro:
* Add something to the shopping list
* Change the quantity in the items to be built, see it works
* Sort by the total cost column
* Change the quantity again
* Notice crash :(

**Comment by Zumochi** [comment]
Followed reproduction steps and had the same issue.

**Comment by Zifrian** [comment]
Awesome, thanks for the repro steps. Others have had this error too and I couldn't reproduce it. I'll get it fixed soon.

**Comment by Regner** [comment]
Glad to be of help. :)

**Comment by Zumochi** [comment]
This issue also applies to the blueprints tab. Sort by total value, change number of runs, crash.

**Comment by Zifrian** [comment]
Bug fixed in 7a27f173b019053da9b3aa0808810729d2878594.
Please close issue. Thanks

**Comment by Regner** [comment]
Thanks for the amazingly quick fix. :)
