### ISSUE TITLE
Mining Boosts outdated

### ISSUE THREAD

**Issue by woothie** [EVEIPH/EVE-IPH#152]
Hi! It seems like the mining tab's fleet booster section is somewhat outdated. Mining Foreman Links are no longer in the game and have been replaced by Mining Foreman Bursts. Initially, I thought it was effectively just a rename and didn't affect the actual boosts, but then I noticed the numbers didn't quite sum up correctly while I had a lovely alliance mate boost me in his Rorqual. I got a higher boost (particularly in cycle time reduction, if I recall correctly) than any skill- and module combination I could assemble in the boost section, so I'm guessing the changes to mining boosts weren't covered by IPH. 
Is this indeed an oversight/down-prioritized section of the program, or is there something I'm missing?

**Comment by Zifrian** [comment]
This has been removed (wasn't doing anything anyway).
