### ISSUE TITLE
Unhandled error when change of quantity in shopping list

### ISSUE THREAD

**Issue by MRartin** [EVEIPH/EVE-IPH#154]
What is your Operating System?                                                                Windows 10 Home 64-bit
What tab or screen did the error occur?                                                     Shoppinglist window -> Items to Build
What are the steps to reproduce the Error?                                                don't know, but the app has been running over 2 days,          and the pc has only been in sleep mode, so the app has not been closed down 
Web link to a screenshot of your error:                                                       https://imgur.com/a/Eixd5b2
In addition to a screenshot, copy the data below and send to developer.

Source: System.Data.SQLite
Message: No current row
Raw Error Text: System.InvalidOperationException: No current row
   ved System.Data.SQLite.SQLiteDataReader.CheckValidRow()
   ved System.Data.SQLite.SQLiteDataReader.GetInt64(Int32 i)
   ved EVE_Isk_per_Hour.ShoppingList.GetNewMatQuantity(ShoppingListItem ItemData, IndustryActivities Activity, Material UpdateMaterial, Int64 NewQuantity)
   ved EVE_Isk_per_Hour.ShoppingList.UpdateShoppingItemQuantity(ShoppingListItem SentItem, Int64 UpdateItemQuantity)
   ved EVE_Isk_per_Hour.frmShoppingList.ProcessKeyDownUpdateEdit(Keys SentKey, ListView ListRef)
   ved EVE_Isk_per_Hour.frmShoppingList.txtListEdit_LostFocus(Object sender, EventArgs e)
   ved System.Windows.Forms.Control.OnLostFocus(EventArgs e)
   ved System.Windows.Forms.Control.WmKillFocus(Message& m)
   ved System.Windows.Forms.Control.WndProc(Message& m)
   ved System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   ved System.Windows.Forms.TextBox.WndProc(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
Having trouble reproducing. Can you make it error or just random?

**Comment by Zifrian** [comment]
This was fixed.
