### ISSUE TITLE
Unhandled error when add additional item in shopping list 

### ISSUE THREAD

**Issue by krower** [EVEIPH/EVE-IPH#155]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System?  Windows 10 Pro 64-bit
What tab or screen did the error occur? Selected blueprint
What are the steps to reproduce the Error? Calculate t2 production. Add 1-3 item to shopping list. Click to "item on shopping list" breaks IPH. (If necessary, I can record a video)
Web link to a screenshot of your error: https://i.imgur.com/YBk5nbG.png
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: Ссылка на объект не указывает на экземпляр объекта.
Raw Error Text: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в EVE_Isk_per_Hour.ShoppingList.CalculateBrokersFees(List`1 ItemList, BrokerFeeInfo BrokerData)
   в EVE_Isk_per_Hour.ShoppingList.SetPriceData(BrokerFeeInfo BrokerFeeData, Boolean IncludeUsage, List`1 ItemBuyTypeList)
   в EVE_Isk_per_Hour.frmShoppingList.LoadFormStats()
   в EVE_Isk_per_Hour.frmShoppingList.chkUsage_CheckedChanged(Object sender, EventArgs e)
   в System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   в System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   в System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   в EVE_Isk_per_Hour.frmShoppingList.InitializeComponent()
   в EVE_Isk_per_Hour.frmShoppingList..ctor()
   в EVE_Isk_per_Hour.frmMain.ShowShoppingList()
   в EVE_Isk_per_Hour.frmMain.pnlShoppingList_Click(Object sender, EventArgs e)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   в System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.StatusStrip.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
This should be fixed now.
