### ISSUE TITLE
Blueprint Management: Item Type filter for Reactions is not working

### ISSUE THREAD

**Issue by tash** [EVEIPH/EVE-IPH#156]
## Observer Behaviour
When selecting **Reactions** under **Item Type** in **Blueprint Management**, the blueprint table is not updated and no formulas are showing.

## Expected behaviour
Given the default selection has not been changed when selecting **Reactions** under **Item Type** in **Blueprint Management**:
* the blueprint table is updated 
* formulas are being displayed

## Steps of reproduction
Open the **Blueprint Management** dialog:
[Edit] > [Manage Blueprints]
*Precondition: the default selections are set.*
Select **Rections** under **Item Type**
![grafik](https://user-images.githubusercontent.com/477569/87928501-3bbe2680-ca85-11ea-8649-340cdf439a68.png)

**Comment by Zifrian** [comment]
Fixed in Build 4.0.7591.19793
