### ISSUE TITLE
Excess Materials List not updated based on build/buy selections

### ISSUE THREAD

**Issue by csatlos** [EVEIPH/EVE-IPH#157]
When calculating a blueprint with, "Calculate Build/Buy" enabled, the Excess Materials List is not updated based on the build/buy selections with the Component Material List on the left side. 

In the example shown below, "Build" has been selected only for the fourth component (Photonic Metamaterials) and "Buy" was selected for the first three components. Based on that selection, there should be no excess Crystalline Carbonide, Phenolic Composites, or Nanotransistors shown in the Excess Materials List.

![eveisk_111120_buildbuy](https://user-images.githubusercontent.com/6238508/98892499-7a318400-246e-11eb-8162-7bb0a3b6f450.png)

**Comment by Zifrian** [comment]
This has been fixed in Build 4.0.7669.37173. Please check your calcs and let me know if something is off. Made a lot of updates to the excess and processing for using reactions to build.
