### ISSUE TITLE
Cost of Charges when Copying to Clipboard

### ISSUE THREAD

**Issue by rsfutch77** [EVEIPH/EVE-IPH#166]
Steps to re-create:

Version 4.0.7790.42119

1. Add more than one run  of any charge blueprints to your shopping list
2. Open the shopping list
3. Select either CSV or SSV export
4. Click the copy list button and paste into Excel or text file or whatever (this is the only method that exports each item to build with the expected sale price of the items)

- [x] Currently the price of modules (1 run to 1 item) calculates correctly. The price of charges calculates the same way, but charges are not 1 run to 1 item, resulting in a lower than expected sale price for all the combined runs of that charge. Note that the total profit for all runs is still calculated correctly at the bottom right of the shopping list. 
- [x] The material volume is calculated in the same manner, except this is actually incorrect in the bottom right of the shopping list.

I've tried it on a variety of charges, old and new. 

The issue is also present on /master at c00a962 - Clean code.

![image](https://user-images.githubusercontent.com/26337219/121468777-36551d80-c970-11eb-912d-c069ca4fe26f.png)

**Comment by rsfutch77** [comment]
I think the issue is here.

![image](https://user-images.githubusercontent.com/26337219/121493255-817d2980-c98c-11eb-8c65-c0bd630ea576.png)

It should be using PortionSize i.e.:
![image](https://user-images.githubusercontent.com/26337219/121494627-c6559000-c98d-11eb-8e7d-578ade3ed022.png)

However I got stuck here and didn't see a quick way to identify the BPBlueprintID for the current item.

**Comment by rsfutch77** [comment]
I'm closer, the issue is here:
https://github.com/EVEIPH/EVE-IPH/blob/c00a962a14222aed88909af80801010e78fa32ed/ShoppingList.vb#L1334-L1341

I would think I can just add `.Runs * .PortionSize`, but then when I do that it fails to print the entire row. 
![image](https://user-images.githubusercontent.com/26337219/121657142-00d63000-ca55-11eb-83e5-153512871c76.png)

**Comment by rsfutch77** [comment]
Nailed it:
https://github.com/rsfutch77/EVE-IPH/commit/55ddf2df6b3432717de67a4a52538f15cc528433

https://github.com/EVEIPH/EVE-IPH/pull/167

**Comment by Zifrian** [comment]
Merged into Build 4.0.7856.41382
