### ISSUE TITLE
Sorting by Profit Percentage Column does not work as expected

### ISSUE THREAD

**Issue by gyrfalcon2138** [EVEIPH/EVE-IPH#17]
I have a general need to do sorts by Profit%, and noticed that the former radio buttons for sorting have been removed from the Manufacturing List. In order to work around this, I added the Profit Percentage column to the Manufacturing list and clicked on it on the assumption my list would be sorted by this column. Unfortunately, it does not seem to be working as I would expect - it seems like Profit% is treating the numbers as strings and ignoring the negative sign:

![image](https://cloud.githubusercontent.com/assets/14957366/11934670/9edf468a-a7d1-11e5-9e48-22554635919c.png)

Issue is on Windows 7 64bit, just updated EVE IPH today

Software Version information:
![image](https://cloud.githubusercontent.com/assets/14957366/11934718/dc3138cc-a7d1-11e5-9220-de4c810fd5c6.png)

**Comment by Zifrian** [comment]
Thanks for the report. Corrected this and uploaded the change in Build 3.1.5833.15919.

**Comment by gyrfalcon2138** [comment]
Awesome - looks good. Thanks for the super fast turn around!
