### ISSUE TITLE
ESI Data Import Error

### ISSUE THREAD

**Issue by d4sd1ng** [EVEIPH/EVE-IPH#173]
Everytime I try to load the Asset Data for the shopping List. I receive an Error Code as shown on the screenshot https://i.imgur.com/zqeFfxS.png

**Comment by hoangphucITJP** [comment]
I got a similar error.
Anyone can help?
![image](https://user-images.githubusercontent.com/14938527/145148771-460dc667-eade-407a-a34a-ee1cbec6305f.png)

**Comment by CanOrhan** [comment]
Temporary solution would be for users to use CCP Data for the time being:
![image](https://user-images.githubusercontent.com/2356269/146113831-1d25ae85-65c3-473e-a54a-f075ca9dc37b.png)

**Comment by Zifrian** [comment]
The asset issue was corrected in a previous release. For the 404's with unknown items, that was fixed in the last update.
