### ISSUE TITLE
Error: "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."

### ISSUE THREAD

**Issue by jasont80** [EVEIPH/EVE-IPH#175]
On starting the application, I'm getting this error. The app will also not download updates or characters, but I'm assuming it's related.

![image](https://user-images.githubusercontent.com/54845351/161602132-af367455-08cc-4e17-ae7a-a012508a73c0.png)

IPH version 5.0.
Win 10 version 21H2

**Comment by funforums** [comment]
I had a similar error when running EVE IPH on linux because I only had dotnet 4.0 installed. Installing Dotnet 4.6.1 fixed it

**Comment by jasont80** [comment]
Thanks for the reply! I guess I'll install 4.6.1 and try again!
