### ISSUE TITLE
Crash on calculating manufacturing list

### ISSUE THREAD

**Issue by feazeyu** [EVEIPH/EVE-IPH#179]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10
What tab or screen did the error occur? Manufacturing list
What are the steps to reproduce the Error? Go to manufacturing list, click calculate with All Blueprints
Web link to a screenshot of your error: 
![Screenshot_354](https://user-images.githubusercontent.com/44237912/186900752-80e2e33a-0618-4c11-96a7-33e593ae91f4.png)
In addition to a screenshot, copy the data below and send to developer.

Source: System.Data.SQLite
Message: Určené přetypování není platné.
Raw Error Text: System.InvalidCastException: Určené přetypování není platné.
   v System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   v System.Data.SQLite.SQLiteDataReader.GetDouble(Int32 i)
   v EVE_Isk_per_Hour.Blueprint.InventREBlueprint(Boolean UseTypical)
   v EVE_Isk_per_Hour.Blueprint.InventBlueprint(Int32 NumLaboratoryLines, Decryptor BPDecryptor, IndustryFacility BPInventionFacility, IndustryFacility BPCopyFacility, Int64 InventionItemTypeID)
   v EVE_Isk_per_Hour.frmMain.DisplayManufacturingResults(Boolean Calculate)
   v EVE_Isk_per_Hour.frmMain.btnCalculate_Click(Object sender, EventArgs e)
   v System.Windows.Forms.Control.OnClick(EventArgs e)
   v System.Windows.Forms.Button.OnClick(EventArgs e)
   v System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ButtonBase.WndProc(Message& m)
   v System.Windows.Forms.Button.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by feazeyu** [comment]
I moved the error window out of the way for better clarity, as its contents are in text

**Comment by Zifrian** [comment]
This should be corrected in the latest patch.
