### ISSUE TITLE
Unable to calculate subsystems in Manufacturing List

### ISSUE THREAD

**Issue by Zumochi** [EVEIPH/EVE-IPH#18]
For a while now, I've been unable to calculate the profits of ALL T3 subsystems in IPH. Doing this via the Blueprints tab works fine but only one at a time :smiley: 

Reproduction steps:
* Open Manufacturing List tab
* With default settings, under Blueprint Type, deselect everything but "Subsystems"
* Preview Item List
* Notice all subsystems are there just fine.
* Calculate
* Receive an empty result list with message "No Blueprints calculated for options selected."

The same thing happens minus the last part if you select other blueprint types as well, however the subsystems simply won't be included.

**Comment by Zifrian** [comment]
Check your settings on SVR threshold or something else that would be filtered after you run calculate. I can't determine everything from the start so a lot of it is done after the bp is calculated.

**Comment by Zumochi** [comment]
Welp, that did it! Just checked "Include items w/o SVR values" and it works :)

How come subsystems don't have those values though?

**Comment by Zifrian** [comment]
It's an EMD api issue, it relies on people uploading stuff and if no one uploads, then it's not there. I'll replace this with CREST soon but there might still be instances of this where no items are sold in that market, which would return nothing.
