### ISSUE TITLE
Unable to see SVR

### ISSUE THREAD

**Issue by shword-dev** [EVEIPH/EVE-IPH#180]
i try reset the market history/orders from the Data menu.
![image](https://user-images.githubusercontent.com/69191290/204368402-df9a8ef1-757b-488f-80e1-eb0b57b70065.png)

**Comment by Zifrian** [comment]
The market history endpoint is down and SVR can't be calculated. CCP is looking at it and no ETA for a fix. I'll update as soon as I get info it's up.

**Comment by LowRentTrent** [comment]
Say, is this issue fixed? My SVR fields are still empty and I'm wondering if I'm just not using the app correctly.

**Comment by Zifrian** [comment]
> Say, is this issue fixed? My SVR fields are still empty and I'm wondering if I'm just not using the app correctly.

It's not up yet. This week we hope but it may be limited for awhile.
