### ISSUE TITLE
Windows Defender detects crypto miner

### ISSUE THREAD

**Issue by labmonkey42** [EVEIPH/EVE-IPH#185]
Latest MSI from eveiph.github.io download link for Windows is flagged for a crypto miner.

![image](https://github.com/EVEIPH/EVE-IPH/assets/10108057/cae551e9-82c1-4ff9-a719-d29b14021e78)

**Comment by Tielem** [comment]
+1 Ran into the same issue

https://www.virustotal.com/gui/file/158a3c52a4457bbf87f210d2422366d5f57b04d29220124c1eed249724945dd5/behavior

Was first scanned 20 september ago. Weird how the creation time of the entry is 3 september though?

**Comment by Zifrian** [comment]
It's a false positive and has been white listed in MacAfee and Windows Defender. I'll get it into a few others on VirusTotal when I have time.

![image](https://github.com/EVEIPH/EVE-IPH/assets/12145310/b4ff466e-0b57-48ae-863b-294fe8971d3f)
