### ISSUE TITLE
Crash when changing Price Profile data.

### ISSUE THREAD

**Issue by bvelasquez** [EVEIPH/EVE-IPH#19]
Changed the region after selecting price profile under the manufactured items tab.

An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug - if you just copy and paste this message, that won't be enough!

What is your Operating System? Windows 7
What tab or screen did the error occur? Manufactured Items in Update Prices using Price Profile
What are the steps to reproduce the Error? Select Price Profile, change Region.
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below for sending to developer.

Source: System.Data.SQLite
Message: SQLite error
near ",": syntax error

**Comment by Zifrian** [comment]
Fix up.

**Comment by bvelasquez** [comment]
Works good now.  Thanks.  You can close this bug.
