### ISSUE TITLE
File corruption in the windows installer of the program

### ISSUE THREAD

**Issue by Darconica** [EVEIPH/EVE-IPH#191]
On startup the program crashes when program is installed using the windows intaller.
But works fine when using the binairy files.

On crashing I get first error message window displating following message : " Unable to get ESI Status: database disk image is malformed. malformed database shema (Imperial Navy Dual Heavy Pulse Laser)."
After closing the error window I get following error: "
An Unhandled Exception has occured and EVE Isk per Hour will now close.
This error occured in EVE IPH Version: 5.0.8930.37040

Please fill out the following information so I can reproduce the bug

What is your Operating System? 
What tab or screen did the error occur? 
What are the steps to reproduce the Error? 
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: database disk image is malformed
malformed database schema (Imperial Navy Dual Heavy Pulse Laser)
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: database disk image is malformed
malformed database schema (Imperial Navy Dual Heavy Pulse Laser) ---> System.Data.SQLite.SQLiteException: database disk image is malformed
malformed database schema (Imperial Navy Dual Heavy Pulse Laser)
   bij System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   bij System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   bij System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   bij System.Data.SQLite.SQLiteDataReader.NextResult()
   bij System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bij System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bij System.Data.SQLite.SQLiteCommand.ExecuteReader()
   bij EVE_Isk_per_Hour.frmMain.DisplayESIStatusMessages()
   bij EVE_Isk_per_Hour.frmMain..ctor()
   --- Einde van intern uitzonderingsstackpad ---
   bij EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   bij EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   bij EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   bij Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   bij Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking: PRAGMA auto_vacuum = FULL; PRAGMA synchronous = NORMAL; PRAGMA locking_mode = NORMAL; PRAGMA cache_size = 10000; PRAGMA page_size = 4096; PRAGMA temp_store = DEFAULT; PRAGMA journal_mode = WAL; PRAGMA count_changes = OFF"

And after closing that error message the program closes itself.

**Comment by Zifrian** [comment]
Thanks, I'll look into it.
