### ISSUE TITLE
T3 Invention cost checkbox doesn't work

### ISSUE THREAD

**Issue by daenmdir** [EVEIPH/EVE-IPH#192]
Pretty much per title. When calculating a T3 blueprint, clicking the invention cost check box does not affect anything on the profit/cost values (see attached screenshot).
![image](https://github.com/user-attachments/assets/4c5fac49-072c-4742-a803-f163174c7faf)

For T2 products, the checkbox applies the invention cost to the material cost properly

**Comment by Zifrian** [comment]
Thanks for the report, I just pushed this fix.
