### ISSUE TITLE
Feature request OR does it exist?

### ISSUE THREAD

**Issue by bvelasquez** [EVEIPH/EVE-IPH#21]
Is it possible to get the ore quantities necessary to fulfill the mineral requirement for a given blueprint job?  For example, I want to build 20 cormorants.  IPH tells me the quantity of minerals.  However, I would like to know exactly how much ore (and what type) I need to refine to fulfill that requirement given my character training/implants.  Maybe there is an easier way to do this?

**Comment by Zifrian** [comment]
Can't do it in the program now but it's on my list to do. I just haven't gotten around to it. The calculations could get pretty involved but I'll get something to try done at some point.

**Comment by bvelasquez** [comment]
I could imagine the calculations could get interesting.  The trick would be to try and get the right ores necessary and the smallest variation within selected regions of space so that your mining activities could be maximized towards your industrial goals. Thank you.

**Comment by Cwittofur** [comment]
I'm in the process of implementing something similar to this. While it is relatively feasible to get an approximation, there is simply no realistic way of getting the margin of error to a low degree. I have basic calculations working now.

Next step is getting station/refine tax, character skills, etc. It's also working mineral by mineral, which in turn causes excess, I'm trying to clean up those calculations (I just wanted to get it to work first!). 

As of right now it is primarily calculating results based off of Null Sec Ores; I will be modifying the database and queries to allow more flexible results. I'll see how accurate I can get, but I wouldn't expect precise values!

**Comment by Cwittofur** [comment]
Just an update; I got it to calculate the ore on a more appropriate basis. It's still generating a bit 'excess' in some areas due to how I am calculating. I'll need to iterate on this a bit more. Station Tax will NOT be in this release. Once I'm satisfied with the calculations then I'll be working on getting a UI component implemented.

**Comment by Cwittofur** [comment]
This is now properly calculating. I've tested it with numerous scenarios and it passed those tests. There are some assumptions that are made (details will be in the release notes when I release.) Closing this issue as it will be solved upon the release this week :)
