### ISSUE TITLE
Copy to clipboard in EVE Multibuy format

### ISSUE THREAD

**Issue by robhaswell** [EVEIPH/EVE-IPH#22]
Since March 2016 EVE has supported reading a list of items into the multibuy window from the clipboard. There are two possible formats

```
Intact Armor Plates 100
Intact Armor Plates 100
```
or
```
100 Intact Armor Plates
100 Intact Armor Plates
```

Seemingly the delimiter can be any form of whitespace.

It would be very convenient if EVEIPH was capable of copying a shopping list into the clipboard using this format.

**Comment by Cwittofur** [comment]
Thank you for your feedback! This is a great idea, I'll work on getting it implemented. I'm going to keep the existing functionality there but there will be a checkbox that you can enable to provide this type of output.

**Comment by Cwittofur** [comment]
This feature has been implemented and is now available via the updater. It can be accessed from the Shopping List window by checking the "Eve List Format" checkbox. When you click "Copy" it will copy the items in the list in the format:

'<item> <quantity>'

**Comment by robhaswell** [comment]
Works great, thanks for the quick implementation!
