### ISSUE TITLE
Use GitHub releases/API for updating

### ISSUE THREAD

**Issue by Pilchard123** [EVEIPH/EVE-IPH#28]
The GitHub API and releases function could be used to manage updating the application. My initial thoughts on implementation are:

On publishing an update:
- Create a new release on GitHub, tagged with the version number. Mark the release ans non-prerelease.
- Include the binaries necessary to install from never having IPH.

On checking for an update:
- Query the [GitHub API releases section](https://developer.github.com/v3/repos/releases/). The latest non-prerelease is found at  api.github.com/repos/EVEIPH/EVE-IPH/releases/latest. Other releases are found at api.github.com/repos/EVEIPH/EVE-IPH/releases.
- Compare the version number for the returned release (X) with that of the currently installed version (Y)
- If X is later than Y, prompt user to download. If accepted,
  - Download the relevant release asset - this would likely be a .zip file or similar
  - Prompt for update now or at next restart. These could probably follow the same process; restarting would be what starts the installation of the update and updating now/later would just be a matter of convenience. The option could be given at startup to skip installing a previously-downloaded update.

On applying the update:
- Start old executable `OE` in root folder `RF`
- Unzip release package to folder `RF\Update`
- Start updated executable `UE` in `RF\Update` with command line parameter `-updateDB` set.
- Close `OE`
- Using `UE`, copy the database from `RF` to `RF\Update`. Overwrite if necessary.
- Update the database if necessary
  - That wouldn't be on every startup, only times when command line parameter `-updateDB` is set.
- Using `UE`, copy the content of `RF\Update` to `RF`. Overwrite if necessary.
- Start copied executable `CE` in `RF` with command line parameter `-cleanUpdate` set.
- Close `UE`
- Using `CE`, delete `RF\Update` and the downloaded zip file.

**Comment by Pilchard123** [comment]
There are a few things that need ironing out with this plan, but I thought I'd get it down on paper (well, kinda) and see what people thought. Below are some other things thought of.

* What happens if the application is closed during a download?
 * Save the file using a one name (e.g. Update.partial) during download, then when the download is finished, rename.
* What happens if the application is closed while applying the update?
 * I don't know. I doubt it would happen, but it might do.
 * Just trust that the user is not going to do that? It's not like it would be difficult to re-download it.
* How should the API be used?
 * [octokit.net](https://github.com/octokit/octokit.net) would work well
  * It's another dependency to keep around
  * It requires .NET 4.5
  * It wouldn't require maintenance.
 * Write API code independently?
  * No dependencies.
  * Why do that when there's already a library out there?
* With a slight change to the process above, it would be possible to allow people to opt in to receiving pre-release updates as well.
* The process above could mean that [the separate update program](https://github.com/EVEIPH/EVE-IPH-Update-Program) would no longer be necessary. I'm not sure if that's a good thing or not.
* It could well be written so that the download and part of the update could be done while the application is still beiong used
* The API could also be used for release notes, by putting them in the description of each release.
* The dependency on MediaFire would be removed
 * But it would be replaced by a dependency on GitHub
* The GitHub Releases API can be accessed without authenticating.
 * It is quite heavily rate-limited if the client does not authenticate.
 * [Conditional requests](https://developer.github.com/v3/#conditional-requests) could mitigate that; the request does not count against the limit if it does not return data.

**Comment by Pilchard123** [comment]
I'm happy to take this on - indeed, I'd quite like to.

**Comment by Cwittofur** [comment]
Thanks for providing this information! I was going to look at using GitHub for releases haha. I'm currently working on a different feature and I don't want to rush the updater code so I think that should be slated for the next release. If possible, I'd like to talk with you about this over TeamSpeak or something at some point!

**Comment by Pilchard123** [comment]
I don't know if TeamSpeak will work. It seems there's quite a time difference between us; you seem to be active around the time when people around me are trying to sleep. Would IRC do the job?

**Comment by Zifrian** [comment]
I'm all for using github but I couldn't find any place where it looked like you could use it as a file server. I guess you can just put the files in the repository but not sure if that violates the TOS. Plus I'd have to do all that work you put up heh.

**Comment by Pilchard123** [comment]
I'll happily take on the update code. The binaries can be uploaded as release assets - that's what that section is for, after all.

**Comment by Zifrian** [comment]
BTW, there is no link to my computer or at least there shouldn't be. As long as the links are the same on the media fire server, it should work fine. Maybe the username/pass change did something on the server but I'm not sure. Anyway, doing whatever is needed to move off a paid server is fine by me.
