### ISSUE TITLE
Manufacturing List Filtering

### ISSUE THREAD

**Issue by beeryt** [EVEIPH/EVE-IPH#29]
Selecting *Owned Blueprints* does not filter out T2 or T3 blueprints that are *unowned*.

![untitled](https://cloud.githubusercontent.com/assets/14947602/14765383/8df9d90a-0994-11e6-8cf6-991e8a242e08.png)

**Comment by beeryt** [comment]
Under *Market Filters* there is an SVR Threshold field that seems fairly obvious in what it does (tooltip helps). However unless "Include Items w/o SVR" is unchecked the filter does nothing. This took me a few minutes to figure out.

**Comment by Zifrian** [comment]
This is by design. Uncheck the 'T2 Invented' and 'T3 Invented' boxes under the 'Include Owned' section and they will go away.

**Comment by Pilchard123** [comment]
So to clarify - do the 'T2 Invented' and 'T3 Owned' boxes say 'behave as if I would invent/RE these blueprints and use them if it could'?

**Comment by Zifrian** [comment]
Yeah, it's an old feature...like 4 years old. People wanted to see what they owned compared to what they could invent/re and how they compared.
