### ISSUE TITLE
Shopping List not updating Items to Buy from Corp Assets

### ISSUE THREAD

**Issue by apes87** [EVEIPH/EVE-IPH#30]
I made a shopping list and wanted to update the amounts I need to buy using "Update with Selected Assets" and selecting corporation Station Warehouse Containers where to pull that information.

I opened up Shopping List, clicked the Safe button to open up the assets selection window.
![iph_02](https://cloud.githubusercontent.com/assets/18037132/14830885/b87cd1aa-0bfb-11e6-9754-dfc91591abc9.png)

IPH is reading the materials and amounts correctly as shown in these screenshots.
![iph_03](https://cloud.githubusercontent.com/assets/18037132/14830910/cffaf29e-0bfb-11e6-9002-dc80b1dda0bb.png)
![iph_04](https://cloud.githubusercontent.com/assets/18037132/14830913/cffb8894-0bfb-11e6-9370-17fb44ed0393.png)
![iph_05](https://cloud.githubusercontent.com/assets/18037132/14830911/cffaefc4-0bfb-11e6-941f-a279b306641b.png)
![iph_06](https://cloud.githubusercontent.com/assets/18037132/14830912/cffb6b02-0bfb-11e6-844a-646afab220be.png)
![iph_07](https://cloud.githubusercontent.com/assets/18037132/14830914/cffc1ee4-0bfb-11e6-86f3-8261beb48c01.png)

I save the settings and click Update with Selected Assets on Shopping List windows but Material amounts do not change at all. Doesn't matter if I only tick the station containers, amounts are not updating. I've ticked everything from system station, office, corp hangar 4 and containers in the screenshots.
If I pull material info from my own item hangar, shopping list updates correctly.
I'm assuming API key is correctly set since it's reading inside the containers.
Station containers are passworded.

I'm running version 3.2.5940.33944
![iph_01](https://cloud.githubusercontent.com/assets/18037132/14830992/3f4505b8-0bfc-11e6-873d-4fec06c2739e.png)

**Comment by Cwittofur** [comment]
Now this is a bug report! <3 I'll look into this tonight. I have an idea what the issue is; just need to debug it :)

**Comment by Cwittofur** [comment]
I just wanted to give you an update on this: 

I have been able to reproduce the issue, unfortunately I'm trying to find a better solution. I was able to temporarily resolve the issue, but it was not a very solid one. I need to look at how the data is represented in the API as items in containers receive special 'terminologies'

**Comment by apes87** [comment]
Great stuff!

**Comment by Cwittofur** [comment]
I have identified a potential fix; I'm testing it a bit further. It's a hack though. The way that the API represents data within a container is complex. To fix the error right off I just check to see if a location id is over a certain range. Which *should* work for the majority of cases.

**Comment by apes87** [comment]
Thanks for the update. You are doing an awesome job!

**Comment by Cwittofur** [comment]
I uploaded the *fix*, please download the update and give it a try :)

**Comment by apes87** [comment]
Yes! It's updating the Shopping list now! Just need to use caution when clicking Update with Selected Assets. When clicked once, everything is updated how it should be. But if I click the button twice, it's updating the amounts again and then they are incorrect.
Shopping List when nothing has been updated.
![nothing updated](https://cloud.githubusercontent.com/assets/18037132/14934326/184ef114-0eb6-11e6-8e07-27aaad8f5c7a.png)
After clicking Update with Selected Assets once.
![clicked once](https://cloud.githubusercontent.com/assets/18037132/14934331/2c844940-0eb6-11e6-8170-d6dc633fd87a.png)
After clicking Update with Selected Assets the second time.
![clicked twice](https://cloud.githubusercontent.com/assets/18037132/14934333/362d719c-0eb6-11e6-87c3-27d0e706d98d.png)

**Comment by Cwittofur** [comment]
Oh! Yeah there should be some extra check logic in there. The shopping list
needs some love. I'll make it a low priority since it is working :)
