### ISSUE TITLE
Refinery Efficiency can only be selected at Refining Skill 5

### ISSUE THREAD

**Issue by TimoDritschler** [EVEIPH/EVE-IPH#38]
It used to be that you needed Refining 5 in order to start training Refinery Efficiency. But by now,
Refinery Efficiency can already be picked up at Refining Skill 4. IPH does not yet reflect that.

**Comment by Cwittofur** [comment]
Could you please elaborate a bit more here? Are you overriding skills? I just did and it worked fine. So I'm not quite sure what the problem is.

**Comment by TimoDritschler** [comment]
When I am on the Mining tab and select "Refining" as skill level 4, the "Refinery Efficiency" dropdown stays grayed-out for me. I need to set Refining to 5 before the efficiency dropdown becomes active.

**Comment by Cwittofur** [comment]
Fixed in version 3.3.5973.39898
