### ISSUE TITLE
Changing ME level on Build/Buy Component Material list

### ISSUE THREAD

**Issue by ResnikSI** [EVEIPH/EVE-IPH#39]
Its not possible to change ME level on some components and build items.

![Bug](http://i.imgur.com/a3JA87K.gif)

Build 3.3.5971.5173

**Comment by Cwittofur** [comment]
You need to press 'Enter' after typing in the number, It doesn't update when the focus is left.

**Comment by ResnikSI** [comment]
Tested it again, with mouse still focused in cell. 

![Bug](http://i.imgur.com/oekXLYp.gif)

Build 3.3.5973.39898

**Comment by Cwittofur** [comment]
Did you enter the text and press the "ENTER" button?

**Comment by ResnikSI** [comment]
yes.

**Comment by Cwittofur** [comment]
I just tested again, I'm still not getting that issue. I click, type in a
new number and press the enter key and it works fine. If I click outside of
the text box (making it lose focus it doesn't work).

**Comment by Zifrian** [comment]
I also tested this out and couldn't get it to error. How are the bps saved? Are they scanned from user, corp, or manually saved?

**Comment by ResnikSI** [comment]
I can check that, but as you can see from first picture, I was able to edit ME in R.A.M - Starship tech, but not in the others.

**Comment by Zifrian** [comment]
Right, I just can't reproduce it. See if it still happens in the latest version I just put up.

**Comment by ResnikSI** [comment]
Can't do it, even after update, anything else I can do from my end to pinpoint the problem?

**Comment by ResnikSI** [comment]
Looks like its fixed now, build 3.3.5984.42133
