### ISSUE TITLE
Double clicking ME in "Items to build" in Shopping List crashes IPH

### ISSUE THREAD

**Issue by ResnikSI** [EVEIPH/EVE-IPH#40]
![Bug](http://i.imgur.com/bwso90z.gif)

> An Unhandled Exception has occured and EVE Isk per Hour will now close.
> 
> Please fill out the following information so I can reproduce the bug
> 
> What is your Operating System? 
> What tab or screen did the error occur? 
> What are the steps to reproduce the Error? 
> Web link to a screenshot of your error: 
> In addition to a screenshot, copy the data below and send to developer.
> 
> Source: System.Data.SQLite
> Message: No current row
> Raw Error Text: System.InvalidOperationException: No current row
>    at System.Data.SQLite.SQLiteDataReader.CheckValidRow()
>    at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
>    at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
>    at EVE_Isk_per_Hour.frmMain.LoadBPfromEvent(Int64 BPID, String BuildType, String Inputs, String SentFrom, IndustryTeam BuildTeam, IndustryTeam ComponentTeam, IndustryTeam CopyTeam, IndustryFacility BuildFacility, IndustryFacility ComponentFacility, IndustryFacility CapCompentFacility, IndustryFacility InventionFacility, IndustryFacility CopyFacility, Boolean IncludeTaxes, Boolean IncludeFees, String MEValue, String TEValue, String SentRuns, String ManufacturingLines, String LaboratoryLines, String NumBPs, String AddlCosts, Boolean PPUCheck, String CompareType)
>    at EVE_Isk_per_Hour.frmShoppingList.lstItems_DoubleClick(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
>    at System.Windows.Forms.ListView.WndProc(Message& m)
>    at EVE_Isk_per_Hour.MyListView.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> Error Tracking: 

Build 3.3.5971.5173

**Comment by Cwittofur** [comment]
Fixed in version: 3.3.5973.39898
