### ISSUE TITLE
Saving shopping lists saves "Items to Build" and the associated materials

### ISSUE THREAD

**Issue by Mav986** [EVEIPH/EVE-IPH#41]
I don't always want a shopping list for building something. Sometimes I want a shopping list for invention only. When saving a shopping list, it seems the "items to build" part takes priority over what appears in the "items to buy" part.

ie. I want a shopping list comprised of 2 different types of datacores only. No manufacturing materials whatsoever. I can create this shopping list by selecting the "invention" radio button in the "Blueprints" tab of the main program. However, after saving that list, and reloading it, it will reload with the datacores, AND all the manufacturing materials.

**Comment by Zifrian** [comment]
I added a fix for this in Build 3.3.5978.26046. 

* Added the 'Rebuild Items when Loading List' to the shopping list window. When selected (Default setting), items saved in your shopping list will be rebuilt and all items will be loaded as if you just added the item but did no adjustments (e.g. removed items or adjusted quantity). When unchecked, the shopping list will load with only the items you originally saved and only update the prices of those items. For example, if you only saved invention materials for a set of items, it will only load those invention materials for the items.

Let me know how it works or doesn't.
