### ISSUE TITLE
EveIPH Updater has stopped working

### ISSUE THREAD

**Issue by egeis** [EVEIPH/EVE-IPH#44]
I was trying to run the updater when it launched but it kept prompting "stopped working."  Windows  kept informing me it needed to be run using "Administrative Privileges, " which I tried using "run as admin" but the same message persisted.  Running the debug I was presented with the following error:

Unhandled exception at 0x7705DAE8 (KernelBase.dll) in EVEIPH Updater.exe: 0xC000041D: An unhandled exception was encountered during a user callback.

**Comment by Cwittofur** [comment]
There's an issue right now with the updater. I'm trying to find a resolution for this :)

**Comment by Zifrian** [comment]
Try deleting the LatestVersionIPH.xml file and rerunning the program and run the update. If that fails, you might need to reinstall. I'm not sure why there was an issue with the updater but it's working on the current version.

Let us know what happens and we can go from there.

**Comment by Galanodel2012** [comment]
Looks like I may be getting a similar error.

Mine states that it is reverting to the old file versions, and that there was an error in the update. The log shows the following error:

System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked

**Comment by Zifrian** [comment]
Yeah I'm working on this. I'm having issues tracking down the issue.

**Comment by Galanodel2012** [comment]
No problem. If there is anything I can do to help, please let me know. I
don't mind taking as many screenshots or testing as many things as you need
:D

**Comment by Zifrian** [comment]
This should be corrected now, however proxy settings have been disabled.
