### ISSUE TITLE
Unhandled Exception when adding new API after install

### ISSUE THREAD

**Issue by rossos** [EVEIPH/EVE-IPH#54]
I just downloaded v3.3, and allowed IPH to self-update. 'About' -> 'About IPH' says that I am running Version 3.3.5996.39804 currently.

Launching the program, I am given the prompt to add a character API. Using the given link (which auto-generates the API key from a mask), I enter my API details, and am given the following:

> An Unhandled Exception has occured and EVE Isk per Hour will now close.
> ...
> Source: EVE Isk per Hour
> Message: Object reference not set to an instance of an object.
> Raw Error Text: System.NullReferenceException: Object reference not set to an instance of an object.
>    at EVE_Isk_per_Hour.frmLoadCharacterAPI.EnterAPI()
>    at EVE_Isk_per_Hour.frmLoadCharacterAPI.btnNext_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> Error Tracking: 

The same error is given if I load IPH without adding an API (letting the program create a dummy character), and then using 'File' -> 'Add Characters'.

Entering an invalid key/verification code does not produce this error.

**Comment by rossos** [comment]
Update: this problem disappeared after a system restart or two. I can no longer reproduce the error.

**Comment by Cwittofur** [comment]
Closing as user reported issue is resolved.
