### ISSUE TITLE
POS 2% job material savings are applied to Station builds while they shouldn't

### ISSUE THREAD

**Issue by saulvin** [EVEIPH/EVE-IPH#57]
In Blueprints tab: select a BPO i.e. "Void L Blueprint".
Total Runs: 1 => 15 Morphite used.
Total Runs: 100 => 1470 Morphite used.
Facility->Activity: Manufacturing
Facility Type: Station
Location: doesn't matter

so from the looks a 2% material reduction is applied.

EIPH Version: 3.3.6009.16436

**Comment by Zifrian** [comment]
This is working as expected. The ME value of 2 on a Void L Blueprint for one run is 15 units of morphite. As you get more runs, the ME value affects the total numbers and at 10, it's 14.7 per run, or 147. For 100, it calculates 10 runs of 10 run bpcs, and you get 1470. The POS numbers are 1450, which applies the extra 2%.

**Comment by saulvin** [comment]
Ok looks my reproduction example was having me getting wrong assumptions. However take this example
Astrahus ME0, 3 runs. Structure components ME7.
EIPH recommends buying 2 of the components while building the others.

find the screenshot attached.

when going with the shopping list one will run short of the following PI materials
2x Wetware Mainframe
1x Self-Harmonizing Power Core
1x Recursive Computing Module
2x Organic Mortar Applications
2x Nano-Factory
3x Broadcast Node

EIPH screenshot is attached as well as parts of wallet transaction log showing that extra materials had to be bought following EIPH's calculation.

So while trying to find a simple example the "float" habbit of material calc's were a bad coincidence

![3runastrahuseiph](https://cloud.githubusercontent.com/assets/17982732/16100215/240dd45e-335d-11e6-97a7-de908021baa7.png)

![materialtransactionlog](https://cloud.githubusercontent.com/assets/17982732/16100297/b84b768a-335d-11e6-8f71-e93f2c1f3d86.png)

**Comment by Zifrian** [comment]
I had a chance to look at this and I don't see the problem. All the numbers in the game using those settings say you need 148 Wetware Mainframes. Are you building them separately or just using one BP? IPH assumes you only have 1 bp to use. I'm not sure why you would need 151 Wetware mainframes. I see no setup that would produce those requirements. Let me know if you are still having an issue but I'm unable to reproduce this issue.
