### ISSUE TITLE
Shopping list Assets not showing Citidel Assets

### ISSUE THREAD

**Issue by kunnis** [EVEIPH/EVE-IPH#58]
When you have assets in a citadel, they do not show up in the Shopping List Assets window.  Reproduction case below.
1. Ingame: Have personal assets in a Citadel.
2. Select a blueprint.
3. Press "Add to Shopping List"
4. At the bottom, double click "Items in Shopping List"
5. Bottom center: click the safe icon

Actual:
The tree of locations doesn't show any citadels.

Expected:
The tree should have a choice for the assets in a citadel.

**Comment by ssiccha** [comment]
I encountered something similar when trying to pull assets from the API. Adding "flat=1" to the AssetList call seems to fix it.

**Comment by Zifrian** [comment]
Yep, that fixes it. I've updated the code to use flat now for assets. Thanks
