### ISSUE TITLE
Update Mining Barges/Exhumers

### ISSUE THREAD

**Issue by richarddewit** [EVEIPH/EVE-IPH#59]
The September 13th update contained a [Mining Barge Overhaul](https://updates.eveonline.com/card/68VxV/mining-barge-overhaul/).

Change were, among others:
* Every MB and Exhumer now have 2 laser hardpoints
* Stats were changed

[More details](https://forums.eveonline.com/default.aspx?g=posts&t=491069)

**Comment by Zifrian** [comment]
Fixed with Build 3.3.6147.22169
