### ISSUE TITLE
Unable to download CREST at startup

### ISSUE THREAD

**Issue by Samael27** [EVEIPH/EVE-IPH#60]
Since the EVE update the 15 November I have this error at the program startup.
![screen shot 11-17-16 at 09 12 am](https://cloud.githubusercontent.com/assets/704088/20381094/27fa13d0-aca6-11e6-84a8-c36d9d2c1e76.PNG)
After everything things working fine but I'm not sure (I don't use the soft log enought to be sure).

I don't know if I can help you more with some logs or something else, let me know.
Thanks

**Comment by Zifrian** [comment]
CCP broke the industry/facilities api and is apparently fixing it.
