### ISSUE TITLE
Ability to add custom Citadels/Engineering complexes in industry

### ISSUE THREAD

**Issue by Keridos** [EVEIPH/EVE-IPH#62]
Would be nice if we could set custom Citadels or Engineering Complexes for calculating industry job costs and ME/TE globally.

**Comment by Strontium-90** [comment]
Now you can emulate Engineering Complex by setting ME/TE of outpost http://i.imgur.com/OJwt79K.png

**Comment by Zifrian** [comment]
This was added with version 4.0
