### ISSUE TITLE
Blueprint filters on manufacturing list do not filter result list properly

### ISSUE THREAD

**Issue by PhillZitt** [EVEIPH/EVE-IPH#63]
![filterissue](https://cloud.githubusercontent.com/assets/1178792/22151475/57897bec-dedb-11e6-924d-60a8bc44947d.PNG)

(The image is sorted by item category ascending)

When filtering the Manufacturing List with the given options, I noticed two issues:
1. In red, there are three (and possibly more) Structure Module that are not being properly filtered.
2. In blue, the Volume Threshold does not appear to be working at all.

**Comment by Zifrian** [comment]
Those are rigs, not structure modules so I limit them when you
check/uncheck rigs. CCP has named them Structure Modules and I think it's a
poor naming convention.

Volume is how many items are sold, not the SVR. Select the volume column
from the selections and you'll see all should have more than 10 units moved.

**Comment by PhillZitt** [comment]
Oh. I'm just a moron then, I can accept that. That is a strange naming convention, I agree.
