### ISSUE TITLE
Hammertime reliability

### ISSUE THREAD

**Issue by Slivo-fr** [EVEIPH/EVE-IPH#64]
Hello there,

I'm not using IPH myself but some friend does, as it often does not start and show up a CREST error, I wanted to take a look at the issue.

It looks like https://stop.hammerti.me.uk isn't reliable and make IPH crash when not available. That the case last two days. 

Maybe you shoud switch to CREST or ESI as CCP work hard to keep them running fine ?
Whatever you will do, you may want to change the error message saying CREST is faulty

**Comment by Samael27** [comment]
I have this issue. Does a fix exist to it ?

**Comment by Zifrian** [comment]
This has been fixed.
