### ISSUE TITLE
Unable to download CREST data for Citadel Information

### ISSUE THREAD

**Issue by nivlac64** [EVEIPH/EVE-IPH#65]
http://i.imgur.com/Jo5wRaX.png

IPH will not even start since it keeps giving the error message. Clicking Ok or the x doesnt do anything. I saw the issue mentioned in the eveo forums earlier in the month, but dont know if theres a fix for this yet

**Comment by Zifrian** [comment]
Please email me your api keys that are causing the issue and I'll see what's happening. Mail to ZifrianEVE@gmail.com

Thanks

**Comment by nivlac64** [comment]
I sent it over. Any luck?

**Comment by Zifrian** [comment]
Yeah, sorry been busy. I'll try to get a fix up tomorrow.

**Comment by Zifrian** [comment]
The fix is up. Let me know if it works.

**Comment by nivlac64** [comment]
awesome. looks like it works now. thanks!
