### ISSUE TITLE
Crash when launching with outdated API Keys

### ISSUE THREAD

**Issue by wreckingadm** [EVEIPH/EVE-IPH#67]
The program was using an API Key for a character that has since been moved to another account. When the program launches I get a message about the API Key not loading properly, then a popup explaining how to generate the API Key with a link to the masked API Key generator page, and then the first popup again. After that the program quits with the following...

> An Unhandled Exception has occured and EVE Isk per Hour will now close.
> 
> Please fill out the following information so I can reproduce the bug
> 
> What is your Operating System? 
> What tab or screen did the error occur? 
> What are the steps to reproduce the Error? 
> Web link to a screenshot of your error: 
> In addition to a screenshot, copy the data below and send to developer.
> 
> Source: EVE Isk per Hour
> Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: The database file is locked
> cannot rollback transaction - SQL statements in progress
> Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The database file is locked
> cannot rollback transaction - SQL statements in progress ---> System.Data.SQLite.SQLiteException: The database file is locked
> cannot rollback transaction - SQL statements in progress
>    at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>    at System.Data.SQLite.SQLiteDataReader.NextResult()
>    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
>    at EVE_Isk_per_Hour.DBConnection.ExecuteNonQuerySQL(String SQL)
>    at EVE_Isk_per_Hour.DBConnection.RollbackSQLiteTransaction()
>    at EVE_Isk_per_Hour.ResearchAgents.UpdateResearchAgents(Boolean UpdateAPI)
>    at EVE_Isk_per_Hour.ResearchAgents.LoadResearchAgents(Boolean UpdatefromAPI)
>    at EVE_Isk_per_Hour.Character.LoadCharacterData(Boolean RefreshAssets, Boolean RefreshBlueprints, Int64 CharacterID)
>    at EVE_Isk_per_Hour.Character.LoadDefaultCharacter(Boolean ReloadAPIData, Boolean RefreshAssets, Boolean RefreshBlueprints, Int64 CharacterID, Boolean OverrideCacheDate)
>    at EVE_Isk_per_Hour.Public_Variables.LoadCharacter(Boolean RefreshAssets, Boolean RefreshBPs)
>    at EVE_Isk_per_Hour.frmMain..ctor()
>    --- End of inner exception stack trace ---
>    at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
>    at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
>    at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
>    at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
>    at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
> Error Tracking: ROLLBACK;

If I could find where the API Key is stored I could wipe it from the config to start fresh, but didn't have any luck with a quick look.

**Comment by Zifrian** [comment]
OBE due to ESI changes. Please see new version at http://eveiph.github.io/
