### ISSUE TITLE
Data Paths

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-IPH#69]
Hi

If you're interested: I've updated your nice program so it puts all files in the roaming directory (a small piece was present, but I rewrote all filename strings to use Path.Combine() to get rid of any path separator issues). 

Due to the buttons not showing I was not be able to run&check the citadel fitting dialog.

At the moment of writing the updater itself is not working (I did not check this separate project out yet).

I also changed the Ignore Minerals checkbox to be treestate so you can ignore all minerals or only high-sec mineable ones.

**Comment by wvdvegt** [comment]
FYI I added further support fit treestate ignore minerals in the manufacturing tab, so it's possible to ignore high-sec minerals in calculations there too.

**Comment by Zifrian** [comment]
I implemented all the changes except the tri-state check for minerals. I'm going to re-look at that whole system anyway. 

Rest of the changes I accepted.
