### ISSUE TITLE
Unhandled exception when changing quantity of items to build in shopping list

### ISSUE THREAD

**Issue by Zumochi** [EVEIPH/EVE-IPH#7]
Unhandled exception occurs when changing the quantity of items to build in the shopping list.

**However**, this is not the case on all items.
For example, changing the quantity of *fuel blocks* to build results in above exception, but changing the quantity of tengus to build works normally.

Exception message: Arithmetic operation resulted in an overflow.

**Comment by Zifrian** [comment]
Thanks. Just put a fix up.

**Comment by Zumochi** [comment]
What's the commit hash for the fix? Confirmed it's fixed though :+1:

**Comment by Zifrian** [comment]
Forgot to commit it. I committed the change with this: ef210e8fae5c45c316db309b64bd29658c9ef7c7
