### ISSUE TITLE
Refining Yield in Mining Tab

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-IPH#70]
Hi,

The refine yield seems a bit off (or better lacking something).

With a MX1003 & RX802 implant and a 54% base yield combined with Refining & Refining Efficiency on 5 I get an 75.3% (from memory) yield (EVE-IPH shows 73.775%).

So 54% (base) *1.15 (reprocessing) *1.1 (efficiency *1.08 (ore) * 1.02 (implant)

The RX802 implant seems to be ignored.

I cannot enter the RX802 I have in the UI. Nor

Btw Refining is called Reprocessing in the Skills.

The implant does

**Comment by Zifrian** [comment]
You have to set the implant in Application Settings and then it will display the value you are looking for. The implant is used in multiple parts of the program. I don't automatically load character implants from ESI.
