### ISSUE TITLE
Feature Request: Add Rorquals to Mining tab

### ISSUE THREAD

**Issue by BaconCatBug** [EVEIPH/EVE-IPH#72]
As title really. Rorquals are the premier mining ship in Eve now.

**Comment by Zifrian** [comment]
I'm not sure how I would add this. They mine with mining drones, which is already a setting you can manually set on the tab.

**Comment by LordMrcS** [comment]
I believe the intention was to be able to simulate only one ship without the multiminers counter and frig/barge ships selector. So I second this feature request instead of opening a new one.

**Comment by fizch** [comment]
Yeah, i would like to see the frigates is ice mining. I don't see an option for that. Perhaps this is something that I can help with, if I ever get free time.

**Comment by Zifrian** [comment]
These features were added.
