### ISSUE TITLE
Support Engineering Complexes as Facility

### ISSUE THREAD

**Issue by SpeedProg** [EVEIPH/EVE-IPH#76]
It would be nice to be able to Select different Engineering Complexes and Rig combinations and the system they are in.
But as alternative it would work for now if you allow setting ME/TE efficiency on POS's (with being allowed to input them very precise).
Currently you can enter ME/TE on Outposts but it only allows a scale of 2.  eg.: 4.76 . While Engineering complexes have multiple boni which must be precalculate and can end up  being a number with a way higher scale. (In my case 4.762)
Also for outposts not every system can be selected.

**Comment by Zifrian** [comment]
Program has been updated for the new structures - see http://eveiph.github.io/ for installer, etc. to get new version.

**Comment by SpeedProg** [comment]
nice gonna try it out later, mad props for updating this for Upwell Structures, must have been a lot of work.
