### ISSUE TITLE
Compressed Ore not adding to shopping list

### ISSUE THREAD

**Issue by aydjay** [EVEIPH/EVE-IPH#78]
Take for example an atron BPO.

Click use compressed ore.

Then click add to shopping list with "Raw Materials" selected. It adds the raw minerals rather than the compressed ore.

**Comment by brinelan** [comment]
I noticed this as well.  Repeatable 100% of the time.

**Comment by Zifrian** [comment]
I've removed compressed ore calcs for now as the numbers were off anyway.
