### ISSUE TITLE
Please add support for other Marketplaces

### ISSUE THREAD

**Issue by RedViper9** [EVEIPH/EVE-IPH#79]
Thanks for building a great program. As Eve-Central has been down for some time, can you please add options to use other API's for market data? EveMarketer, EVE Swagger and Evepraisal all seem to be reasonable options.

**Comment by Zifrian** [comment]
The CCP Data option pulls from the game data and still works.

**Comment by Zifrian** [comment]
Program has been updated to use ESI and EVE Marketer - see http://eveiph.github.io/ for installer, etc. to get new version.
