### ISSUE TITLE
"download prices" does not update any prices

### ISSUE THREAD

**Issue by Jan02** [EVEIPH/EVE-IPH#81]
"download prices" does not update any prices
tried both eve central and ccp data

**Comment by aydjay** [comment]
Works for me. Maybe you have a firewall blocking?

**Comment by indy10** [comment]
I really love this program, but recently i've had issues with pricing as well. I've noticed that a lot of minerals and some of the other resources come back with prices 0.01 This kind of breaks the program. Is there a way we can import prices using CCP or another website?

**Comment by indy10** [comment]
I may have found the resolve. Instead of selecting Jita as the trade hub select The Forge (Jita). Finally got min buy/sell prices for minerals.

**Comment by Jan02** [comment]
this worked for me:

![eve isk per hour_2018-02-24_01-06-07](https://user-images.githubusercontent.com/2181218/36626339-06dfbe22-18ff-11e8-91ff-d0f0436a3342.png)

**Comment by Zifrian** [comment]
Program has been updated to use ESI and EVE Marketer - see http://eveiph.github.io/ for installer, etc. to get new version.
