### ISSUE TITLE
Relies on now shutdown XML

### ISSUE THREAD

**Issue by ficti0n1** [EVEIPH/EVE-IPH#83]
Not sure if you are aware but eve's XML API has shut down. It now exclusively uses ESI api.

This makes this program, sadly, broken.

Thanks for the years of use.

**Comment by fritzlolpro** [comment]
Hi. Will you continue to develop this awesome program? There is a option to move to esi

**Comment by Zifrian** [comment]
I've completed the ESI conversion and now finishing up the new facilities object. I'll have an update soon.

**Comment by fritzlolpro** [comment]
Very good news, I really enjoy IPH, it's the best industry tool. Thank you

**Comment by nigel10005** [comment]
Zif,

So glad you are still working on this. If you need any help with testing etc (my VB skills are only trained to -1) please shout.

**Comment by Meigs2** [comment]
Oh god would I LOVE to see EVE-IPH updated to modern ESI/Citadel standards. Thank you so much.

**Comment by craneworks** [comment]
Any ETA for the new release?

**Comment by Zifrian** [comment]
Program has been updated with ESI - see http://eveiph.github.io/ for installer, etc.
