### ISSUE TITLE
ESI tutorial page 404'd

### ISSUE THREAD

**Issue by anhility** [EVEIPH/EVE-IPH#84]
Hello.
https://eveiph.github.io/ESIAuthorizationInstructions.html is not working and the software keeps throwing me errors for using the wrong URI string for ESI callbacks when trying to download character info.
Could you please reupload the instructions or at least make a note or something of what URI string that is required?

**Comment by Zifrian** [comment]
I'm testing right now. I'll put up a base page and let everyone know when it's ready.

**Comment by anhility** [comment]
Thanks for the quick reply.
Used your software a lot when I played a few years ago and recently came back to EVE.
Keep up the good work!

**Comment by Zifrian** [comment]
Program has been updated  - see http://eveiph.github.io/ for installer, etc.
