### ISSUE TITLE
oAuth without firewall issues

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-IPH#88]
Btw if you want to oAuth login without starting web servers and run into firewall issues, an easier way might be following the URL that an embedded browser is trying to display (with events like OnNavigate or alike).

The last one (just before the redirect to localhost:port) already contains the token you need to verify the pilot in the URL. Just stop/close the browser when you got the token.

**Comment by Zifrian** [comment]
I was asking around about doing this but an embedded browser would allow me to get the login information and password of thr user account, which I wouldnt do but i’m not comfortable building code for.

I’ll check closing the browser option you suggested.
