### ISSUE TITLE
Behaviour change: T2 with Raw Materials

### ISSUE THREAD

**Issue by nigel10005** [EVEIPH/EVE-IPH#89]
In v3, manufacturing calcs using "Raw Materials" only went as deep as Advanced Moon Materials. In v4 the materials list now includes Raw Moon Materials, materials for the Fuel Blocks required to react those materials, etc.

Have I missed a setting? Or would it be possible to add a "Depth Control" switch?

**Comment by Zifrian** [comment]
This us fixed now in the latest version.
