### ISSUE TITLE
Using BP Filter in Blueprints List gives SQLite error

### ISSUE THREAD

**Issue by SpeedProg** [EVEIPH/EVE-IPH#92]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Source: System.Data.SQLite
Message: SQLite error
ambiguous column name: BLUEPRINT_NAME
Raw Error Text: System.Data.SQLite.SQLiteException (0x80004005): SQLite error
ambiguous column name: BLUEPRINT_NAME
   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   bei System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader()
   bei EVE_Isk_per_Hour.frmBlueprintList.SetTopNodes()
   bei EVE_Isk_per_Hour.frmBlueprintList.btnRefresh_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
What were you searching for? I can't get it to error with numerous option changes. Do you have a screenshot to reproduce the error?

**Comment by SpeedProg** [comment]
Seems to work at the newest version now.
