### ISSUE TITLE
Opening Upwell Structure Fitting window crashes

### ISSUE THREAD

**Issue by eve-n0rman** [EVEIPH/EVE-IPH#95]
An Unhandled Exception has occurred and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10
What tab or screen did the error occur? Upwell Structure Fitting
What are the steps to reproduce the Error? Open Raitaru fitting from Manufacturing List tab
Web link to a screenshot of your error: https://i.imgur.com/6Xf1A9V.png
In addition to a screenshot, copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: Input string was not in a correct format.
Raw Error Text: System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
Error Tracking:

**Comment by Zifrian** [comment]
What were the rigs you had fit on the structure?

**Comment by eve-n0rman** [comment]
It was a Raitaru with Advanced Medium, Large and Component I ME rigs.

**Comment by eve-n0rman** [comment]
And Manufacturing, Research and Invention services

**Comment by Zifrian** [comment]
I still can't get this to error. What BP where you looking at? Can you send a screen of your settings on the form?

**Comment by eve-n0rman** [comment]
It occurs with any blueprint.  As soon as I open the structure fit window it crashes.   I'd rather not share more detailed screenshots publically.  Are you available in game or on discord somewhere?

**Comment by Zifrian** [comment]
Fixed with Build 4.0.6727.20751
