### ISSUE TITLE
EVE IPH crashed now I can't select a character

### ISSUE THREAD

**Issue by Zyles** [EVEIPH/EVE-IPH#99]
When I re-open the program after a crash the character list is blank.

I click the login to eve button and authorize, and it opens up my browser (which can't connect to the port) with the auth code.

And then it sits and "Loading character data from ESI" forever.

When I terminate the program it says "Character failed to load"

**Comment by nigel10005** [comment]
I had the "could not connect to port" problem yesterday. Try following the first answer on this page <https://social.technet.microsoft.com/Forums/en-US/0face535-3c7a-4658-be34-6c376322ca34/microsoft-edge-cant-open-local-domains?forum=win10itpronetworking> and see if that solves it.

**Comment by Zifrian** [comment]
Closing. Reopen if the error still exists.
